# Generated by Django 2.1.3 on 2018-11-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='observacao',
            new_name='observacoes',
        ),
    ]
