# Generated by Django 2.1.3 on 2018-11-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20181126_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descricao',
            new_name='nome',
        ),
    ]
